export const HEADER = "font-ibm-medium text-5xl"
export const SUBHEADER = "font-ibm-medium text-[2.4rem]"
export const TITLE = "font-ibm-medium text-2xl"
export const PARAGRAPH = "font-ibm text-base"
export const LABEL = "font-ibm text-sm"
export const BUTTON = "font-ibm-semibold"