# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "StarterBase.xcodeproj")
    build_app(
  workspace: "StarterBase.xcworkspace",
  scheme: "StarterBase",
  configuration: "Release",
  export_options: {
    provisioningProfiles: {
      "com.okmoney.gotroger" => "AppStore_com.okmoney.gotroger.mobileprovision"
    }
  }
)
    upload_to_testflight
  end
end
